version: '2'

networks:
  studentnet01:
    ipam:
      config:
        - subnet: 172.20.1.0/24

services:
  studentmachine01:
    image: studentmachine:latest
    ##build: .
    container_name: studentmachine01
    environment:
      - TZ=Europe/Berlin
    ports:
      - "22001:22"
    networks:
      studentnet01:
        ipv4_address: 172.20.1.2

  sshmachine01:
    image: sshmachine:latest
    #build: .
    container_name: sshmachine01
    environment:
      - TZ=Europe/Berlin
    ports:
      - "23001:22"
    networks:
      studentnet01:
        ipv4_address: 172.20.1.3

  sshmachine01a:
    image: sshmachine:latest
    #build: .
    container_name: sshmachine01a
    environment:
      - TZ=Europe/Berlin
    networks:
      studentnet01:
        ipv4_address: 172.20.1.4

 
