version: '2'

networks:
  ros:
    driver: bridge

services:
  ros-core-master:
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  talker-master:
    image: talker_master:latest
    depends_on:
      - ros-core-master
    environment:
      - "ROS_MASTER_URI=http://ros-core-master:11311"
      - "ROS_HOSTNAME=talker_master"
    command: /bin/bash -c "source /app/devel/setup.bash && rosrun talker talker"
    networks:
      - ros
    restart: always

  listener-master:
    image: listener_master:latest
    depends_on:
      - ros-core-master
    environment:
      - "ROS_MASTER_URI=http://ros-core-master:11311"
      - "ROS_HOSTNAME=listener_master"
    command: /bin/bash -c "source /app/devel/setup.bash && rosrun listener listener"
    networks:
      - ros
    restart: always
